server {
  listen 80;
  server_name shenyuhan.online www.shenyuhan.online ai.shenyuhan.online;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  http2 on;
  server_name shenyuhan.online;

  ssl_certificate /etc/letsencrypt/live/shenyuhan.online/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/shenyuhan.online/privkey.pem;

  root /var/www/root;

  location = / {
    try_files /index.html =404;
  }

  location / {
    return 404;
  }
}

server {
  listen 443 ssl;
  http2 on;
  server_name www.shenyuhan.online;

  ssl_certificate /etc/letsencrypt/live/shenyuhan.online/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/shenyuhan.online/privkey.pem;

  return 301 https://shenyuhan.online$request_uri;
}

server {
  listen 443 ssl;
  http2 on;
  server_name ai.shenyuhan.online;

  ssl_certificate /etc/letsencrypt/live/shenyuhan.online/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/shenyuhan.online/privkey.pem;

  return 503;
}
